/** Declaration file generated by dts-gen */

export function filterAll(source: any, fields: any): any;

export function filterObject(object: any, fields: any): any;

export function filterObjects(objects: any, fields: any): any;

